version: '3'
services:
   peer1:
      build: ./peer/
      ports:
         - 8001:8001
      environment:
         - PEER_PORT=6001
         - HTTP_PORT=8001
   peer2:
      build: ./peer/
      ports:
         - 8002:8002
      environment:
         - PEERS=peer1:6001
         - PEER_PORT=6002
         - HTTP_PORT=8002