version: '3'
services:
   peer1:
      image: databasserne/block-chain
      ports: 
         - 6001:6001
      environment:
         - PEER_PORT=6001
   peer2:
      image: databasserne/block-chain
      ports:
         - 6002:6002
      links:
         - peer1
      environment:
         - PEERS=peer1:6001
         - PEER_PORT=6002
